name: Lint

on:
  push:
    branches:
      - master
  pull_request:

env:
  PYTHON_MIN_VERSION: "3.7.13"

jobs:
  asdf-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_MIN_VERSION }}
      - run: scripts/install_dependencies.bash
      - run: scripts/lint.bash --check

  asdf-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      - name: Install dependencies
        run: go get ./...
      - name: Run 'gofumpt'
        run: go run mvdan.cc/gofumpt -l -w .
      - name: Check format
        run: '[ -z "$(gofmt -l ./...)" ]'
      - name: Run 'revive'
        run: go run github.com/mgechev/revive -set_exit_status ./...
      - name: Vet
        run: go vet ./...
      - name: Lint
        run: go run honnef.co/go/tools/cmd/staticcheck -tests -show-ignored ./...
      - name: Build
        run: go build -v ./...

  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.24
        with:
          args: -color
