name: Lint

on:
  push:
    branches:
      - master
  pull_request:

env:
  PYTHON_MIN_VERSION: "3.7.13"

jobs:
  asdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_MIN_VERSION }}
      - run: scripts/install_dependencies.bash
      - run: scripts/lint.bash --check

  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.24
        with:
          args: -color
